baseurl         = "/"
theme           = "sp-minimal"
languageCode    = "en-us"
title           = "Curso"
disqusShortname = ""
paginate        = 5
ignoreFiles     = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title       = "Curso de Introducción a la Inferencia Causal en Epidemiología"
  subtitle    = "29-30 Octubre,<br>Escuela Andaluza de Salud Pública, Granada"
  copyright   = "Released under the MIT license."
  authorImage = "logo.png"

  #"single" or "multi"
  renderType = "single"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = ""

  name = ""
  description = "Miguel Ángel Luque-Fernández <br> Daniel Redondo-Sánchez"
  pageNotFoundTitle = "404 - Page not found"