baseurl         = "/"
theme           = "sp-minimal"
languageCode    = "en-us"
title           = "Curso Inferencia Causal"
disqusShortname = ""
paginate        = 5
ignoreFiles     = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title       = "Curso de Introducción a la Inferencia Causal en Epidemiología"
  subtitle    = ""
  copyright   = "Released under the MIT license."
  authorImage = "logo.png"

  #"single" or "multi"
  renderType = "single"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = "UA-121938065-1"

  name = ""
  description = "3 de septiembre, 2019<br>Facultad de Medicina y Ciencias de la Salud de Oviedo<br>Curso precongreso SEE"
  pageNotFoundTitle = "404 - Page not found"